
env:
 - GHCVER=7.6.3 CABALVER=1.18
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=7.10.2 CABALVER=1.22
 - GHCVER=head CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=head

before_install:
 - mkdir -p $HOME/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L http://download.fpcomplete.com/michael/cabal-meta.tar.gz | tar xz -C $HOME/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - ./.travis-setup.sh
 - cabal --version

install:
    - ghc --version
    - cabal --version
    - sudo apt-get install libfcgi-dev
    - travis_retry cabal update
    - cabal unpack wai-logger
    - mv wai-logger-* wai-logger
    - cabal install hspec doctest HTTP temporary
    - cabal-meta install --force-reinstalls

script: mega-sdist --test
