language: haskell

install:
    - cabal unpack wai-logger-2.1.1
    - cp sources-travis.txt sources.txt
    - cabal install mega-sdist hspec cabal-meta cabal-src
    - cabal-meta install --force-reinstalls

script: mega-sdist --test
