resolver: lts-4.1
packages:
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./wai-app-static
- ./wai-handler-fastcgi
- ./wai-handler-launch
- ./wai-websockets
- ./wai-conduit
- ./mime-types
- ./auto-update
extra-deps:
- http2-1.6.0
- cryptonite-0.23
- memory-0.14.6
- tls-1.3.11
- fast-logger-2.4.5
- wai-logger-2.2.7
- http-types-0.9.1
- x509-1.6.5
- x509-validation-1.6.5
- foundation-0.0.12
- tls-session-manager-0.0.0.1
- psqueues-0.2.3.0
nix:
  enable: false
  packages:
  - fcgi
  - zlib
image:
  containers:
    - base: "fpco/pid1"
      name: "yesodweb/warp"
      executables:
        - warp
