resolver: lts-4.1
packages:
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./wai-app-static
- ./wai-handler-fastcgi
- ./wai-handler-launch
- ./wai-websockets
- ./wai-conduit
- ./mime-types
- ./auto-update
extra-deps:
- http2-1.5.0
- cryptonite-0.13
- memory-0.11
nix:
  enable: false
  packages:
  - fcgi
  - zlib
